version: '3.8'

services:
  # MariaDB Database
  db:
    image: mariadb:10.11
    container_name: goldexperte-dev-db
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_NAME:-goldexperte_pimcore}
      MYSQL_USER: ${DB_USER:-pimcore}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pimcore_password}
    volumes:
      - goldexperte-dev-db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-file-per-table=1
      - --max-connections=200
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u${DB_USER:-pimcore} -p${DB_PASSWORD:-pimcore_password} ${DB_NAME:-goldexperte_pimcore} -e 'SHOW TABLES;'"]
      interval: 10s
      retries: 6
      start_period: 1m
      timeout: 3s
    networks:
      - goldexperte-dev-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: goldexperte-dev-redis
    ports:
      - "127.0.0.1:6379:6379"
    command: 
      - redis-server
      - --maxmemory 128mb
      - --maxmemory-policy volatile-lru
      - --save ""
    networks:
      - goldexperte-dev-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: goldexperte-dev-elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - bootstrap.memory_lock=true
    volumes:
      - goldexperte-dev-elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - goldexperte-dev-network

  # PHP-FPM
  php:
    image: pimcore/pimcore:php8.2-debug-latest
    container_name: goldexperte-dev-php
    user: "${DOCKER_USER:-1000:1000}"
    environment:
      COMPOSER_HOME: /var/www/html
      PHP_IDE_CONFIG: serverName=localhost
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
      PIMCORE_ENVIRONMENT: ${PIMCORE_ENVIRONMENT:-dev}
      
      # Pimcore Installation Config
      PIMCORE_INSTALL_MYSQL_USERNAME: ${DB_USER:-pimcore}
      PIMCORE_INSTALL_MYSQL_PASSWORD: ${DB_PASSWORD:-pimcore_password}
      PIMCORE_INSTALL_MYSQL_PORT: 3306
      PIMCORE_INSTALL_MYSQL_HOST_SOCKET: db
      PIMCORE_INSTALL_MYSQL_DATABASE: ${DB_NAME:-goldexperte_pimcore}
      PIMCORE_INSTALL_ADMIN_USERNAME: ${PIMCORE_ADMIN_USER:-admin}
      PIMCORE_INSTALL_ADMIN_PASSWORD: ${PIMCORE_ADMIN_PASSWORD:-admin_password}
      
      # Services
      REDIS_URL: "redis://redis:6379"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      MAILER_DSN: ${MAILER_DSN:-smtp://mailhog:1025}
      
    volumes:
      - ./pimcore:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - goldexperte-dev-network

  # Nginx Web Server
  nginx:
    image: nginx:stable-alpine
    container_name: goldexperte-dev-nginx
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./pimcore:/var/www/html:ro
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - goldexperte-dev-network

  # Supervisor for Background Tasks
  supervisor:
    image: pimcore/pimcore:php8.2-supervisord-latest
    container_name: goldexperte-dev-supervisor
    user: "${DOCKER_USER:-1000:1000}"
    environment:
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
      PIMCORE_ENVIRONMENT: ${PIMCORE_ENVIRONMENT:-dev}
      REDIS_URL: "redis://redis:6379"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    volumes:
      - ./pimcore:/var/www/html
      - ./docker/supervisor/dev.conf:/etc/supervisor/conf.d/pimcore.conf:ro
    depends_on:
      - db
      - redis
      - php
    networks:
      - goldexperte-dev-network

  # MailHog for Email Testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: goldexperte-dev-mailhog
    ports:
      - "127.0.0.1:8025:8025"  # Web interface
      - "127.0.0.1:1025:1025"  # SMTP server
    networks:
      - goldexperte-dev-network

volumes:
  goldexperte-dev-db-data:
  goldexperte-dev-elasticsearch-data:

networks:
  goldexperte-dev-network:
    driver: bridge
