#cloud-config

# Cloud-init configuration for Goldexperte Pimcore server
hostname: ${hostname}

# Update and upgrade packages
package_update: true
package_upgrade: true

# Install essential packages
packages:
  - curl
  - wget
  - git
  - htop
  - vim
  - ufw
  - fail2ban
  - unattended-upgrades
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# Configure automatic updates
write_files:
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Automatic-Reboot "false";
      Unattended-Upgrade::Automatic-Reboot-Time "02:00";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";

  - path: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

# Configure fail2ban
  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 3
      
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3

# Setup Docker installation script
  - path: /root/install-docker.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # Install Docker
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      systemctl enable docker
      systemctl start docker
      usermod -aG docker root

# Basic firewall setup
runcmd:
  # Configure UFW
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw --force enable
  
  # Install Docker
  - /root/install-docker.sh
  
  # Mount data volume (if present)
  - |
    if [ -b /dev/sdb ]; then
      mkdir -p /mnt/pimcore-data
      if ! blkid /dev/sdb; then
        mkfs.ext4 /dev/sdb
      fi
      mount /dev/sdb /mnt/pimcore-data
      echo '/dev/sdb /mnt/pimcore-data ext4 defaults 0 2' >> /etc/fstab
      chown -R root:root /mnt/pimcore-data
      chmod 755 /mnt/pimcore-data
    fi
  
  # Enable and start fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Create deployment directory
  - mkdir -p /opt/goldexperte-pimcore
  - chown root:root /opt/goldexperte-pimcore
  
  # Set timezone
  - timedatectl set-timezone Europe/Vienna

# Configure SSH (optional hardening)
ssh_pwauth: false
disable_root: false

# Reboot after setup
power_state:
  delay: "+1"
  mode: reboot
  message: "Rebooting after cloud-init setup"
  timeout: 30
  condition: true
